# Generated by Django 5.1 on 2024-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='combos',
            field=models.ManyToManyField(blank=True, to='order.combo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='offers',
            field=models.ManyToManyField(blank=True, to='order.offer'),
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='order',
            name='combos',
            field=models.ManyToManyField(blank=True, to='order.combo'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='order.OrderItem', to='order.dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(blank=True, to='order.offer'),
        ),
    ]
