# Generated by Django 5.1 on 2024-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_topproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=0.0, upload_to='meals/'),
            preserve_default=False,
        ),
    ]
