# Generated by Django 5.1 on 2024-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='Address',
            field=models.TextField(default='xyz ', max_length=200),
        ),
        migrations.AddField(
            model_name='usercopy',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=30),
        ),
    ]
