# Generated by Django 5.1 on 2024-10-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_usercopy_address_usercopy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='combos',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='combos',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
