# Generated by Django 5.1 on 2024-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_offer_discount_percentage_offer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_lat', models.FloatField()),
                ('restaurant_lng', models.FloatField()),
                ('delivery_radius', models.FloatField(help_text='Delivery radius in kilometers')),
            ],
        ),
    ]
