# Generated by Django 5.1 on 2024-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the image', max_length=100)),
                ('image', models.ImageField(help_text='Upload an image', upload_to='gallery_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='special_price',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='dishes/noodles.png', null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default=125, upload_to='offers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
