# Generated by Django 5.1 on 2024-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_userinfo_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
